<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>XML Sitemap</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <style type="text/css">
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      font-size: 14px;
      color: #333;
      line-height: 1.6;
      margin: 0;
      padding: 20px;
      background-color: #f8f9fa;
    }
    .container {
      max-width: 1200px;
      margin: 0 auto;
      background: white;
      border-radius: 8px;
      box-shadow: 0 2px 10px rgba(0,0,0,0.1);
      overflow: hidden;
    }
    .header {
      background: #2c3e50;
      color: white;
      padding: 30px;
      text-align: center;
    }
    .header h1 {
      margin: 0 0 10px 0;
      font-size: 28px;
      font-weight: 600;
    }
    .header p {
      margin: 0;
      opacity: 0.9;
      font-size: 16px;
    }
    .stats {
      background: #34495e;
      color: white;
      padding: 15px 30px;
      display: flex;
      justify-content: space-between;
      font-size: 14px;
    }
    .table-container {
      overflow-x: auto;
    }
    table {
      width: 100%;
      border-collapse: collapse;
    }
    th {
      background: #f8f9fa;
      padding: 15px;
      text-align: left;
      font-weight: 600;
      border-bottom: 2px solid #e9ecef;
      color: #2c3e50;
    }
    td {
      padding: 15px;
      border-bottom: 1px solid #e9ecef;
    }
    tr:hover {
      background: #f8f9fa;
    }
    .url {
      color: #3498db;
      font-weight: 500;
    }
    .priority {
      background: #e8f5e8;
      color: #27ae60;
      padding: 4px 8px;
      border-radius: 4px;
      font-size: 12px;
      font-weight: 600;
    }
    .changefreq {
      background: #e3f2fd;
      color: #1976d2;
      padding: 4px 8px;
      border-radius: 4px;
      font-size: 12px;
      font-weight: 600;
    }
    .footer {
      text-align: center;
      padding: 20px;
      color: #6c757d;
      font-size: 14px;
      border-top: 1px solid #e9ecef;
    }
    .section-title {
      background: #f8f9fa;
      padding: 10px 30px;
      margin: 0;
      font-weight: 600;
      color: #2c3e50;
      border-bottom: 1px solid #e9ecef;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>XML Sitemap</h1>
      <p>Generated by P2M Solutions - This is an XML Sitemap, meant for consumption by search engines.</p>
    </div>
    
    <div class="stats">
      <div>This XML Sitemap contains <strong><xsl:value-of select="count(urlset/url)"/></strong> URLs</div>
      <div>Generated on: <strong><xsl:value-of select="current-dateTime()"/></strong></div>
    </div>

    <div class="table-container">
      <table>
        <thead>
          <tr>
            <th style="width: 50%">URL</th>
            <th style="width: 15%">Last Modified</th>
            <th style="width: 15%">Change Frequency</th>
            <th style="width: 10%">Priority</th>
          </tr>
        </thead>
        <tbody>
          <!-- Main Pages -->
          <tr><td colspan="4" class="section-title">🏠 Main Pages</td></tr>
          <xsl:for-each select="urlset/url[contains(loc, '/') and not(contains(loc, '/service/')) and not(contains(loc, '/projects/')) and not(contains(loc, 'privacy') or contains(loc, 'terms') or contains(loc, 'refund'))]">
          <tr>
            <td><a href="{loc}" class="url"><xsl:value-of select="loc"/></a></td>
            <td><xsl:value-of select="lastmod"/></td>
            <td><span class="changefreq"><xsl:value-of select="changefreq"/></span></td>
            <td><span class="priority"><xsl:value-of select="priority"/></span></td>
          </tr>
          </xsl:for-each>

          <!-- Service Pages -->
          <tr><td colspan="4" class="section-title">🛠️ Services</td></tr>
          <xsl:for-each select="urlset/url[contains(loc, '/service/')]">
          <tr>
            <td><a href="{loc}" class="url"><xsl:value-of select="loc"/></a></td>
            <td><xsl:value-of select="lastmod"/></td>
            <td><span class="changefreq"><xsl:value-of select="changefreq"/></span></td>
            <td><span class="priority"><xsl:value-of select="priority"/></span></td>
          </tr>
          </xsl:for-each>

          <!-- Project Pages -->
          <tr><td colspan="4" class="section-title">🚀 Projects</td></tr>
          <xsl:for-each select="urlset/url[contains(loc, '/projects/') and loc != 'https://p2msolutions.com/projects']">
          <tr>
            <td><a href="{loc}" class="url"><xsl:value-of select="loc"/></a></td>
            <td><xsl:value-of select="lastmod"/></td>
            <td><span class="changefreq"><xsl:value-of select="changefreq"/></span></td>
            <td><span class="priority"><xsl:value-of select="priority"/></span></td>
          </tr>
          </xsl:for-each>

          <!-- Legal Pages -->
          <tr><td colspan="4" class="section-title">⚖️ Legal Pages</td></tr>
          <xsl:for-each select="urlset/url[contains(loc, 'privacy') or contains(loc, 'terms') or contains(loc, 'refund')]">
          <tr>
            <td><a href="{loc}" class="url"><xsl:value-of select="loc"/></a></td>
            <td><xsl:value-of select="lastmod"/></td>
            <td><span class="changefreq"><xsl:value-of select="changefreq"/></span></td>
            <td><span class="priority"><xsl:value-of select="priority"/></span></td>
          </tr>
          </xsl:for-each>
        </tbody>
      </table>
    </div>

    <div class="footer">
      <p>You can find more information about XML sitemaps on <a href="https://www.sitemaps.org" target="_blank">sitemaps.org</a></p>
    </div>
  </div>
</body>
</html>
</xsl:template>
</xsl:stylesheet>